version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules # Éviter d'écraser node_modules
      - /app/dist # Empêcher la synchronisation des fichiers build
      - /app/.angular/cache # Empêcher le cache de bloquer le reload
    command: ["npm", "start"]
